name: WorldEditSync
version: '${project.version}'
main: dev.twme.worldeditsync.paper.WorldEditSyncPaper
api-version: '1.13'
depend:
  - WorldEdit
description: Sync WorldEdit clipboard across servers
permissions:
  worldeditsync.sync:
    description: Sync WorldEdit clipboard across servers
    default: true